apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
stringData:
  # Replace with your GitHub Personal Access Token with repo scope
  GITHUB_ACCESS_TOKEN: "YOUR_GITHUB_ACCESS_TOKEN"

---

apiVersion: v1
kind: Pod
metadata:
  name: gh-runner-flashattention
spec:
  # The pod will be automatically restarted by the kubelet if it fails.
  restartPolicy: Always
  # Select a node with the correct architecture and a GPU.
  # For x86/amd64:
  nodeSelector:
    kubernetes.io/arch: amd64
  # For ARM/aarch64, you would use:
  # nodeSelector:
  #   kubernetes.io/arch: arm64
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
  containers:
  - name: gh-runner-flashattention
    # Use the appropriate image for your architecture.
    # For x86/amd64:
    image: gueraf/self_hosted_cuda_runner:latest
    # For ARM/aarch64:
    # image: gueraf/self_hosted_cuda_runner:arm
    command: ["/bin/bash", "-c"]
    args:
      - |
        set -e
        # The runner agent files are often in a directory like this.
        # If the image has a different layout, this path may need to be adjusted.
        cd /home/docker/actions-runner

        # Install jq if it's not already in the image.
        if ! command -v jq &> /dev/null; then
          # This assumes the image uses apt. If it uses a different package manager,
          # this command will need to be changed.
          apt-get update && apt-get install -y jq
        fi

        # Request a runner registration token from the GitHub API.
        REG_TOKEN=$(curl -fsS -X POST -H 'Accept: application/vnd.github+json' -H "Authorization: token ${GITHUB_ACCESS_TOKEN}" https://api.github.com/repos/gueraf/flash-attention/actions/runners/registration-token | jq -r '.token')

        if [[ -z "${REG_TOKEN}" || "${REG_TOKEN}" == "null" ]]; then
          echo "Failed to obtain a runner registration token from GitHub." >&2
          exit 1
        fi

        # Set runner name and labels.
        # For x86/amd64:
        RUNNER_NAME=${NODE_NAME}
        RUNNER_LABELS="self-hosted,Linux,X64,gpu,${NODE_NAME}"
        # For ARM/aarch64, you would use:
        # RUNNER_LABELS="self-hosted-arm,Linux,ARM64,gpu,${NODE_NAME}"

        # Configure the runner.
        ./config.sh --url https://github.com/gueraf/flash-attention --token ${REG_TOKEN} --name ${RUNNER_NAME} --labels ${RUNNER_LABELS} --unattended

        # Start the runner.
        ./run.sh
    env:
    # The GitHub Personal Access Token is passed from the secret.
    - name: GITHUB_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-secret
          key: GITHUB_ACCESS_TOKEN
    # The node name is used to give the runner a unique name.
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    volumeMounts:
    # Mount a memory-backed emptyDir to /dev/shm to provide a larger shared memory space.
    - name: dshm
      mountPath: /dev/shm
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 8Gi